### PR TITLE
your readme is too long I'm lazy

### PR DESCRIPTION
**Pull request by nano1412**
UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU UwU

### CODE REVIEW

**Comment by MaFIaTH** [comment]
Ummmmm.... WHATTT???

**Comment by nano1412** [comment]
I mean come on who gonna read that

**Comment by MaFIaTH** [comment]
You just played AAT for many many hours and you can't read README.md???

**Comment by nano1412** [comment]
Yes

**Comment by nano1412** [comment]
at least give me a break I don't want to read all day you know

**Comment by MaFIaTH** [comment]
Ok. Noted.


NOT!!!

**Comment by nano1412** [comment]
I still able to comment here you know

**Pull request closed without merging**
